/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	RCC_AHB1ENR |= (1<<1);
	GPIOB_MODER &= ~(3<<30);
	GPIOB_MODER |= (1<<30);
	GPIOB_MODER &= ~(3<<28);
	GPIOB_MODER |= (1<<28);
	GPIOB_MODER &= ~(3<<26);
	GPIOB_MODER |= (1<<26);
    /* Loop forever */
	for(;;)
	{
		// Type 1
		GPIOB_ODR &= ~(1<<15);
		for (uint32_t i = 0; i<300000; i++);
		GPIOB_ODR |= (1<<15);
		for (uint32_t i = 0; i<300000; i++);
		GPIOB_ODR &= ~(1<<14);
		for (uint32_t i = 0; i<300000; i++);
		GPIOB_ODR |= (1<<14);
		for (uint32_t i = 0; i<300000; i++);
		GPIOB_ODR &= ~(1<<13);
		for (uint32_t i = 0; i<300000; i++);
		GPIOB_ODR |= (1<<13);
		for (uint32_t i = 0; i<300000; i++);

		// Type 2
		/*GPIOB_ODR ^= (1<<15);
		for (uint32_t i = 0; i<300000; i++);
*/

	}
}
