/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdint.h>
#include "stm32.h"

void gpio_initialise()
{
	RCC_AHB1ENR |= (1<<1);
	RCC_AHB1ENR |= (1<<2);

	//OUTPUT Configuration
	GPIOB_MODER &= ~(3<<26);
	GPIOB_MODER |= (1<<26);	// Port B 13 as OUTPUT

	//INPUT Configuration
	GPIOB_MODER &= ~(3<<14);	//PORT B 7 as Input

	//port c
	GPIOC_MODER &= ~(3<<18);
	GPIOC_MODER |= (1<<18);
	GPIOB_ODR &=~(1<<13);
}
int main(void)
{
	gpio_initialise();

	/* Loop forever */

	for(;;)
	{
		//Switch Interface without debounce
		if(!(GPIOB_IDR & (1<<7)))
		{
			if(!(GPIOB_IDR & (1<<7)))
			{
//			GPIOC_ODR |= (1<<9);
			for(uint32_t i=0; i<50000;i++);
			while((GPIOB_IDR & (1<<7))){}
			}
		}
//		else
//		{
//			GPIOB_ODR |=(1<<13);
//			GPIOC_ODR &= ~(1<<9);
//			for(uint32_t i=0; i<50000;i++);
//		}
		}
	}

