/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


/******PROCEDURE************/
/* Step 1: Identify the bus clock , APB1 bus (UART4), AHB1 (PORTA)*/
/*Step 2: Config PORTA for UART4 PA0-> TX, PA1->RX*/
/* 2.1-> Select Mode of operation for PA0 & PA1 as alternate fn*/
/* 2.2-> AFRL alternate function as AF8 (PA0 & PA1)*/
/*2.4-> select speed as high speed in PA0 & PA1*/
/*Step 3: config UART*/

char rx_data[20];
uint8_t ind=0;

void USART2_config()
{
	/*UART port pin config*/
	RCC->AHB1ENR |= (1<<0);			// enable GPIOA clock
	GPIOA->MODER &= ~(0xF<<4);		// enable alternate fn in PA0 & 1
	GPIOA->MODER |=(0xA<<4);
	GPIOA->AFR[0] &= ~(0xFF<<8);	// enable UART4 TX & RX function for PA0 & PA1
	GPIOA->AFR[0] |= (0x77<<8);
	GPIOA->OSPEEDR |= (0xF<<4);		// set output speed as high speed
	/*UART4 config */
	RCC->APB1ENR |= (1<<17); 		// enable UART4 clock
	USART2->CR1 |= (1<<13); 			//Uart4 is enabled
	USART2->CR1 &= ~(1<<12); 		//set 8bit data mode
 	USART2->BRR = 0x683;				// baudrate for 9600
 	USART2->CR1 |= (1<<5); 			//Uart4 Rx interrupt enable
 	USART2->CR1 |= (3<<2); 			// TE & RE enable
 	NVIC_EnableIRQ(USART2_IRQn);		// UART4 Rx interrupt enable in NVIC
}

void USART2_sendchar(uint8_t x)
{
	USART2->DR = x;						/*Please the data in DR register for transmitting*/
	while(!(USART2->SR & (1<<6)));		/*Wait until TC (Transmission complete) is 1*/
}

void USART2_sendstring(char *string)
{
	while(*string)
	{
		USART2_sendchar(*string++);
	}
}

void USART2_IRQHandler()
{
	while(!(USART2->SR & (1<<5)));		/*wait until RXNE bit is set which indicates data receive*/
	rx_data[ind]=USART2->DR;
	ind++;
	rx_data[ind]='\0';
}

int main(void)
{
	USART2_config();
		USART2_sendstring(" WELLCOME");
		USART2_sendstring(" ALL");
}
