/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32_timer.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	//while(!(RCC_CR & (1<<1)));	// Checking HSI Ready (ref manual 161 )

	RCC_AHB1ENR |= (1<<1);
	GPIOB_MODER &= ~((3<<30)|(3<<28));	//PB14 & PB15 as output
	GPIOB_MODER |= (1<<30)|(1<<28);
	GPIOB_OTYPER &= ~((1<<15)|(1<<14));
	GPIOB_OSPEEDR &= ~((3<<30)|(1<<28));

	GPIOB_ODR &= ~(1<<15);		//PB15 LED ON (led2)
	GPIOB_ODR |= (1<<14);		//PB14 LED OFF (led 3)

	for(uint32_t i=0; i<200000;i++);	//some delay

	RCC_CR |= (1<<16);		// Enable External oscillator (HSE)
	//RCC_CR &= ~(1<<16);
	while(!(RCC_CR & (1<<17)));	// Checking HSE Ready

	GPIOB_ODR &= ~(1<<14);		//PB14 LED ON
	GPIOB_ODR |= (1<<15);		//PB15 LED OFF

    /* Loop forever */
	for(;;)
	{

	}
}
