/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//IRQ at P3

#include "stm32f4xx.h"
#include <stdint.h>
uint32_t count=0;
void EXTI3_IRQHandler(void)
{
    if (((EXTI->PR)>>3) & 1){	//RM 386

    	count=count+1;
    	 GPIOB->ODR ^= (1 <<13);
    	 for(int j=0; j<10000; j++);
        EXTI->PR = (1 << 3);
    }
}
int main(void)
{
    RCC->AHB1ENR |= (1 << 1);
    GPIOB->MODER &=~(3<<26);
    GPIOB->MODER &=~(3<<28);
    GPIOB->MODER &=~(3<<30);
    GPIOB->MODER |=(1<<26);
    GPIOB->MODER |=(1<<28);
    GPIOB->MODER |=(1<<30);
    GPIOB->MODER &= ~(3<<6); //switch
    RCC->APB2ENR |= (1 << 14); //  for enable GPIO RM 187
    SYSCFG->EXTICR[0] |= (1<<12); // bport PB[x] port 3 RM297
    EXTI->RTSR |= (1<<3); //Rising trigger selection  switch is connected PB3 RM 385
    EXTI->IMR |= (1<<3); // interrupt NON maskable  RM 384
    NVIC_SetPriority(EXTI3_IRQn, 1); //STM32 header file
    NVIC_EnableIRQ(EXTI3_IRQn); //enable or called handler
    while(1)
    {
    }
    return 0;
}
