/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void led_initialise()
{
		RCC->AHB1ENR |= (1<<1);		//enable GPIOB clock
		GPIOB->MODER &= ~((3<<30)|(3<<26));	//PB15 & PB13as output
		GPIOB->MODER |= (1<<30)|(1<<26);
		GPIOB->OTYPER &= ~((1<<15)|(1<<13));	// push pull
		GPIOB->OSPEEDR &= ~((3<<30)|(1<<26));	// low speed
		GPIOB->ODR |= (1<<15)|(1<<13);		//PB15 & PB13 LED OFF
}
void timer3_initialise()
{
		RCC->APB1ENR |= (1<<1);		//TIM3 clock enable
		TIM3->PSC = 16000-1;			//Loading prescaler for 1KHz output
		TIM3->ARR = 1000-1;				//load ARR to get 1Hz Output
		TIM3->CNT = 0;				// reset counter register
		TIM3->DIER |= (1<<0);		// Enable update Interrupt 632
		TIM3->CR1 |= (1<<0);		// Start Timer 3
}

void TIM3_IRQHandler()
{
		if(TIM3->SR & (1<<0))		// Confirm update interrupt rm 633
		{
			GPIOB->ODR ^= (1<<15);	// Toggle LED PB15
			TIM3->SR &= ~(1<<0);	// clear flag
		}
}

int main(void)
{
	led_initialise();
	timer3_initialise();
	NVIC_EnableIRQ(TIM3_IRQn);		// Enable Timer 3 Interrupt
	/* Loop forever */
	for(;;)
	{
		/* Blinking LED 4 at PB13 randomly to show that
		 * for loop delay is not affecting timer delay
		 * when using interrupt
		 */
		GPIOB->ODR ^= (1<<13);
		for(uint16_t i =0; i<50000;i++);
	}
}
