/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void gpio_initialise()
{
		RCC_AHB1ENR |= (1<<2);		//enable GPIOC clock
		GPIOC_MODER &= ~(3<<12);	//clear PC6 mode bits
		GPIOC_MODER |= (2<<12);		// Alternate function for PC6
		GPIOC_AFRL &= ~(0xF<<24);	//clear PC6 AFRL bits
		GPIOC_AFRL |= (0x2<<24);	// PC6 alternate fn as TIM3 CH1
		GPIOC_OTYPER &= ~(1<<6);	// PC6 push pull
		GPIOC_OSPEEDR &= ~(3<<12);	// PC6 clear speed
		GPIOC_OSPEEDR |= (1<<12);	// PC6 medium speed
}

void timer3_initialize()
{
		RCC_APB1ENR |= (1<<1);		// enable TIM3 clock // RM 183
		TIM3_PSC = 0;
		TIM3_ARR = 16000-1;			// Timer Output 1KHz
		TIM3_CNT=0;					// Reset Counter
		TIM3_CCMR1 &= ~(7<<4);		// Clear Output mode in TIM3 CH1
		TIM3_CCMR1 |= (6<<4);		// Set PWM mode 1 for TIM3 CH1 output RM 678
		TIM3_CCMR1 |= (1<<3);		// Enable CCR preload 	RM 678
		TIM3_CCER |= (1<<1);		// Active LOW Polarity enable RM 576
		TIM3_CCER |= (1<<0);		//	Send timer output to PC6 RM 576
		TIM3_EGR |= (1<<0);			// Update all registers RM 635
		TIM3_CR1 |= (1<<7);			// Auto preload enable page number RM 672
		/*CCR value (PWM OUTPUT) = ARR value x (duty cyle in percentage)*/
		//TIM3_CCR1 =(uint32_t)((TIM3_ARR * 10)/100); // load duty cycle for PWM
		TIM3_CR1 |= (1<<0);			// Start timer page number RM 672
}

	void tim3_pc6_set_dutycycle(uint32_t freq, uint32_t duty_cycle, uint8_t channel)
	{
	TIM3_ARR=(16000000/freq-1);
	switch(channel)
	{
	case 1:
		TIM3_CCR1 = (uint32_t)((TIM3_ARR * duty_cycle)/100);	//period = (ARR)*(clock cycle)
		break;
	case 2:
			TIM3_CCR1 = (uint32_t)((TIM3_ARR * duty_cycle)/100);
			break;
	case 3:
				TIM3_CCR1 = (uint32_t)((TIM3_ARR * duty_cycle)/100);
				break;
	default:
			break;

	}
	}
int main(void)
{


	gpio_initialise();

	timer3_initialize();
	while(1)
	{
		 tim3_pc6_set_dutycycle(1000,80,1); ////duty_cycle = ((CCR1/(ARR+1))
		 for(int i=0;i<300000;i++);
		 tim3_pc6_set_dutycycle(1000,40,1);
			 for(int i=0;i<300000;i++);
			 tim3_pc6_set_dutycycle(1000,10,1);
				 for(int i=0;i<300000;i++);
	}


	/* Loop forever */
	for(;;)
	{

	}
}
